import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Sora, Inter } from 'next/font/google';
import "./globals.css";

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora', // Define a CSS variable for Tailwind
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "TECHMONKEYS",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/assets/LogoImg.png' },
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} ${geistSans.variable} ${geistMono.variable} ${inter.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
