"use client"
import CountUp from '../Animations/Countup';
import React, { useState, useRef, MouseEvent } from 'react';
import TestimonialCard from '@/Components/Cards';
import {Avatar, AvatarFallback, AvatarImage, } from "../Components/ui/avatar"

type Slide = {
  superTitle: string;
  title: string;
  subtitle: string;
  websiteUrl: string;
};

interface Testimonial {
  name: string;
  title: string;
  text: string;
  rating: number;
  avatarUrl: string;
}

const slidesData: Slide[] = [
  {
    superTitle: "Explore Our Portfolio",
    title: "Website Redesign for a Sartawi Properties",
    subtitle: "Unlock growth, efficiency, and innovation with future-ready technology solutions tailored to your unique needs.",
    websiteUrl: "https://www.sartawiproperties.com/", 
  },
  {
    superTitle: "Explore Our Portfolio",
    title: "Website Redesign for a Sartawi Properties",
    subtitle: "Unlock growth, efficiency, and innovation with future-ready technology solutions tailored to your unique needs.",
    websiteUrl: "https://www.sartawiproperties.com/", 
  },
  {
    superTitle: "Explore Our Portfolio",
    title: "Website Redesign for a Sartawi Properties",
    subtitle: "Unlock growth, efficiency, and innovation with future-ready technology solutions tailored to your unique needs.",
    websiteUrl: "https://www.sartawiproperties.com/", 
  },
];

const cardData = [
    { title: "Total Projects", value: 80 },
    { title: "Total Clients", value: 35 },
    { title: "Client Reviews", value: 25 },
];


const testimonialsCardData: Testimonial[] = [
  {
    name: "Osman",
    title: "CEO, Auto Breeze Car Rental",
    text: "Partnering with Tech Monkey was one of the best decisions for our car rental firm. Their expertise in building our website and mobile app has transformed the way we manage our database and serve our customers. With their seamless solutions and intuitive designs, our operations have become more efficient, and our customers love the user-friendly experience.As a firm started by the former VP of Deutsche Bank, we sought nothing but excellence, and Tech Monkey delivered beyond expectations. Their professionalism, technical expertise, and commitment to innovation are truly commendable. Highly recommended!",
    rating: 5,
    avatarUrl: "https://www.techmonkey.us/clientpics/osman.jpg",
  },
  {
    name: "Vivi, Dubai, United Arab Emirates",
    title: "Owner, Tutor",
    text: "Tech Monkey has been a game-changer for Tutor. As a platform connecting freelancers with clients, we needed a robust and intuitive website that caters to both sides seamlessly. Tech Monkey delivered exactly that, creating an admin model for freelancers and a user-friendly base website for clients, ensuring a flawless experience for all.Their team brought unparalleled expertise, creativity, and technical precision to the table. Thanks to Tech Monkey, Tutor now has a digital platform that perfectly reflects our mission and drives meaningful connections. We couldn’t be happier with the results!",
    rating: 5,
    avatarUrl: "https://www.techmonkey.us/clientpics/vivi.jpg",
  },
  {
    name: "Maria, Barcelona, Spain",
    title: "Manager, Urban Skyline Hotel",
    text: "Tech Monkey delivered an exceptional website that brings our AI brand’s mission to life. As a leading AI company in Spain, focused on highlighting the differences between content generated by ChatGPT and Gemini, we needed a platform that was both visually striking and highly functional.Tech Monkey’s team exceeded our expectations by creating a seamless, user-friendly website that effectively communicates our expertise and innovation. Their professionalism, creativity, and dedication to our vision have helped us establish a strong digital presence. We couldn’t have asked for a better partner!",
    rating: 4,
    avatarUrl: "https://www.techmonkey.us/clientpics/maria.jpg",
  },
  {
    name: "Achyut , Kathmandu Nepal",
    title: "Owner, The Laughing Sherpa",
    text: "Tech Monkey has been instrumental in bringing The Laughing Sherpa's vision to life. Our mission to empower farmers in Nepal by bringing their products to the global market required a robust and impactful e-commerce platform, and Tech Monkey delivered just that.The website they built for us is not only visually stunning but also incredibly functional, enabling seamless transactions and showcasing our story of sustainability and community impact. Their dedication to understanding our values and translating them into a digital experience is truly remarkable.Thanks to Tech Monkey, we’re making a difference while connecting with customers worldwide!",
    rating: 5,
    avatarUrl: "https://www.techmonkey.us/clientpics/achyut.jpg",
  },
];


export default function Home() {
  const [activeIndex, setActiveIndex] = useState(0);


  const sliderRef = useRef<HTMLDivElement>(null);
  const [isDown, setIsDown] = useState(false);
  const [startX, setStartX] = useState(0);
  const [scrollLeft, setScrollLeft] = useState(0);

  const handleMouseDown = (e: MouseEvent<HTMLDivElement>) => {
    if (!sliderRef.current) return;
    setIsDown(true);
    sliderRef.current.classList.add('active');
    setStartX(e.pageX - sliderRef.current.offsetLeft);
    setScrollLeft(sliderRef.current.scrollLeft);
  };

  const handleMouseLeave = () => {
    if (!sliderRef.current) return;
    setIsDown(false);
    sliderRef.current.classList.remove('active');
  };

  const handleMouseUp = () => {
    if (!sliderRef.current) return;
    setIsDown(false);
    sliderRef.current.classList.remove('active');
  };

  const handleMouseMove = (e: MouseEvent<HTMLDivElement>) => {
    if (!isDown || !sliderRef.current) return;
    e.preventDefault();
    const x = e.pageX - sliderRef.current.offsetLeft;
    const walk = (x - startX) * 2; // The multiplier increases scroll speed
    sliderRef.current.scrollLeft = scrollLeft - walk;
  };

  return (
    <div className="bg-[#0F0F0F] flex items-center justify-center pt-15">

      <div className="relative w-full max-w-3xl max-h-3xl aspect-[4/3] bg-[#0F0F0F] rounded-4xl shadow-2xl py-4 px-4 flex flex-col border-3 border-white ">

        <div className=" h-full overflow-y-auto mt-4 pr-2 no-scrollbar">
          {/* Hero Section */}
          <div className="bg-cover bg-no-repeat text-white p-7 animated-background bg-gradient-to-r from-[#AC7C00] via-[#0F0F0F] to-[#AC7C00]">
            <div className="items-center">
              <div className="flex justify-center items-start pt-5 animate-[fadeInLeft_1s_ease-out]">
                <img src="https://www.techmonkey.us/_next/image?url=%2Ftechmonkeys2.png&w=640&q=75" alt="Your Company Logo" width={120} height={50}/>
              </div>
              <div className='flex flex-row gap-12 pt-13'>
                  <div className='w-2/3 animate-[fadeInLeft_1s_ease-out]'>
                    <p className='text-2xl text-left font-normal'>
                      Grow your Business with </p>
                      <h1 className='text-2xl mb-2 text-amber-200'>Tech Monkeys</h1>
                    
                    <p className='text-sm'>Unlock growth, efficiency, and innovation with future-ready technology solutions.</p>
                    <div className='pt-6 '>
                      <button className='bg-white text-black text-xs font-medium px-8 py-2 rounded-2xl'>Enquire Now</button>
                    </div>
                  </div>
                <div className='w-1/3 bg-amber-300 rounded-lg text-sm text-black h-full p-4'>

                  <div className='animate-[fadeInLeft_2s_ease-out]'>
                    <div className="flex flex-row flex-wrap items-center gap-12">
                      <div className="*:data-[slot=avatar]:ring-background flex -space-x-2 *:data-[slot=avatar]:ring-2 *:data-[slot=avatar]:grayscale">
                        <Avatar>
                          <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
                          <AvatarFallback>CN</AvatarFallback>
                        </Avatar>
                        <Avatar>
                          <AvatarImage src="https://github.com/leerob.png" alt="@leerob" />
                          <AvatarFallback>LR</AvatarFallback>
                        </Avatar>
                        <Avatar>
                          <AvatarImage
                            src="https://github.com/evilrabbit.png"
                            alt="@evilrabbit"
                          />
                          <AvatarFallback>ER</AvatarFallback>
                        </Avatar>
                      </div>
                    </div>

                    <p>
                      Trusted by more than 25 founders across the globe
                    </p>
                    <button className='text-xs underline flex'>View Testimonials -</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/*Our Associations Section */}
          <div className="bg-white py-5">
            <h2 className="text-center text-xl text-gray-800">Our Associations</h2>
            <div className='flex flex-row justify-between px-3 pt-5'>
              <img src="https://www.techmonkey.us/_next/image?url=%2Fgoogle%20cloud.png&w=640&q=75" alt="Google" width={100} height={50} />
              <img src="https://www.techmonkey.us/_next/image?url=%2Faws.png&w=256&q=75" alt="AWS" width={100} height={50} />
              <img src="https://www.techmonkey.us/_next/image?url=%2Fadobe.png&w=640&q=75" alt="Adobe" width={100} height={50} />
              <img src="https://www.techmonkey.us/_next/image?url=%2FSAP.png&w=640&q=75" alt="SAP" width={100} height={50} />
              <img src="https://www.techmonkey.us/_next/image?url=%2Fsalesforce.png&w=640&q=75" alt="Salesforce" width={100} height={50} />
            </div>
          </div>

          {/* Porfolio Section */}
          <div>
             <section className="flex items-center justify-center bg-black p-4 py-4">
              <div className="relative w-full max-w-6xl overflow-hidden rounded-2xl">
                
                {/* Main Content & Image Container */}
                <div className="relative h-[500px] md:h-[450px]">
                  {slidesData.map((slide, index) => (
                    <div
                      key={index}
                      className={`absolute inset-0 transition-opacity duration-700 ease-in-out ${
                        activeIndex === index ? 'opacity-100' : 'opacity-0'
                      }`}
                    >
                      <div className="bg-gradient-to-br from-[#FFD34D] to-[#B48700] h-full flex flex-row gap-3">
                        
                        {/* Left Side: Text Content */}
                        <div className="basis-xl justify-between text-black p-5">
                          <div>
                            <span className="mb-6 inline-block rounded-full bg-yellow-300/30 px-2 py-2 text-xs border border-white">
                              {slide.superTitle}
                            </span>
                            <h1 className="text-3xl leading-tight">
                              {slide.title}
                            </h1>
                            <p className="text-sm pt-3">{slide.subtitle}</p>
                          <div className="mt-4">
                            <button className="rounded-4xl bg-gray-900 px-4 py-2 text-white text-xs transition hover:bg-gray-800">
                              View Project
                            </button>
                          </div>
                          </div>

                        </div>

                        {/* Right Side: Embed */}
                        <div className="text-black basis-lg relative h-full md:block">
                          <iframe
                            src={slide.websiteUrl}
                            title={slide.title}
                            width={400}
                            height={600}
                            scrolling='no'
                            className=" scale-[.85] origin-bottom-right rounded-tl-[40px]"
                            loading="lazy"
                          />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Bottom Navigation Dots */}
                <div className="absolute bottom-10 left-6 z-10 flex items-center space-x-3">
                  {slidesData.map((_, index) => (
                    <button
                      key={index}
                      onClick={() => setActiveIndex(index)}
                      className={`h-2 rounded-full transition-all duration-300 ${
                        activeIndex === index ? 'w-8 bg-black' : 'w-2 bg-white'
                      }`}
                      aria-label={`Go to slide ${index + 1}`}
                    />
                  ))}
                </div>
              </div>
            </section>
          </div>

          {/* Services Section */}
          <div className='px-7 pt-20 pb-96 text-center'>
            <h1 className='text-2xl pb-4'>Our Services</h1>
            <p className='text-sm'>At Tech Monkey, we deliver innovative, tailored solution to meet your business needs. Our experienced team ensures every solution address current demands and supports future growth. We specialize in key tech areas that help your business stay competitive and thrive in digital-first world.</p>
          </div>

          {/* About Us Section */}
          <div className='bg-[#141414]'>
            <div className='px-10 text-center py-10'>

              <h1 className='text-2xl pb-4'>About Us</h1>
              <p className='text-xs tracking-wider'>Tech Monkey is a dynamic tech company founded by Varun, an Oxford MBA with extensive expertise in entrepreneurship, and Jainam, a visionary entrepreneur who co-built and sold their IT startup to Amazon alongside Varun. Together, they bring over eight years of combined experience in IT, sales, and CRM, creating a foundation of innovation and excellence. Headquartered in Dubai, with offices in the United Kingdom and the United States, Tech Monkey specializes in developing customized technology solutions tailored to the needs of modern businesses. Our mission is to empower organizations to thrive in a digital-first world by streamlining processes, enhancing customer experiences, and driving sustainable growth. At Tech Monkey, Varun and Jainam's unique blend of technical expertise and strategic insight fuels our commitment to delivering cutting-edge solutions. Together, they lead a team dedicated to shaping the future of IT with creativity, precision, and impact.</p>
              
            </div>

            {/*Cards */}
            <div className='p-10 flex gap-4'>
              {cardData.map((card) => (
                <div key={card.title} className="w-1/3 h-full rounded-md bg-gradient-to-br from-yellow-300 to-black p-0.5">
                  <div className="w-full h-full rounded-md bg-black p-6 font-thin">
                    <h3 className="text-sm font-medium mb-2">{card.title}</h3>
                    <p className="text-2xl font-bold">
                      <CountUp
                        from={1}
                        to={card.value}
                        separator=","
                        direction="up"
                        duration={0.5}
                        className="count-up-text"
                      />+
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Testimonials */}
          <div className='bg-[#0F0F0F] py-10 bg-radial-[at_50%_125%] from-yellow-600 to-zinc-900 to-75%'>
            <h1 className='text-2xl flex justify-center items-center'>Testimonials</h1>
              <style>{`.hide-scrollbar::-webkit-scrollbar {
                display: none;
                }
                .hide-scrollbar {
                  -ms-overflow-style: none;
                  scrollbar-width: none;
                }`}
              </style>
            
            <div className="flex items-center justify-center overflow-hidden">
              <div 
                className="hide-scrollbar overflow-x-auto flex space-x-8 p-8 md:p-12 cursor-grab active:cursor-grabbing select-none w-full"
                ref={sliderRef}
                onMouseDown={handleMouseDown}
                onMouseLeave={handleMouseLeave}
                onMouseUp={handleMouseUp}
                onMouseMove={handleMouseMove}
              >
                {testimonialsCardData.map((testimonial, index) => (
                  <TestimonialCard key={index} testimonial={testimonial} />
                ))}
              </div>
            </div>
          </div>

          {/* Footer Section */}
          <div className='bg-[#141414] p-15 '>
            <div>
              <p className='text-2xl font-bold '>Do you have</p>
              <p className='text-2xl font-bold pb-4'>any questions?</p>
              <p className='text-xs pb-4'>Feel free to send us your question or request a free consultation</p>
              <button className='py-1.5 px-4 bg-[#FFC43C] text-xs text-black rounded-lg'>Send a message</button>
              <div className='text-gray-500 text-xs py-12'>Disclaimer +</div>
            </div>

            <div className='text-xs flex gap-6'>
              <div>Services</div>
              <div>Pricing</div>
              <div>Sale</div>
              <div>Blog</div>
              <div>Contacts</div>
            </div>

            <div className='py-8 flex justify-between'>
              <div className='grid grid-cols-2 gap-8'>
                <div>
                  <div className='text-xs text-gray-500'>SIGN UP</div>
                  <div className='text-xs'>+971 585857795</div>
                  <div className='text-xs'>+971 585605980</div>
                </div>
                <div>
                  <div className='text-xs text-gray-500'>OPENING HOURS</div>
                  <div className='text-sm'>24/7</div>
                </div>
                <div >
                  <div className='text-xs text-gray-500'>EMAIL</div>
                  <div className='text-sm'>support@techmonkey.us</div>
                </div>
              </div>
              <div className='text-right pt-15'>
                <div className='text-yellow-400 text-lg'>TECHMONKEYS</div>
                <div className='text-xs text-gray-500'>At Tech Monkey, we specialize in delivering a range of innovative solutions tailored to meet your business needs</div>
                <div className='text-xs text-gray-500'>© 2024 — Copyright</div>
              </div>
            </div>
          </div>

        </div> 
      </div> 
    </div> 
  );
}
